GO         = go
GOGET      = $(GO) get -u
GOTEST    ?= go test
GOFLAGS   ?= -mod=vendor
GOPATH    ?= $(HOME)/go

export GOFLAGS

#######
# Debug flags

DEBUG_GRID = DEBUG_GRID=1
DEBUG_OBJECT_LABELS = DEBUG_OBJECT_LABELS=1
DEBUG_ROOM_STRUCTURE = DEBUG_ROOM_STRUCTURE=1 
DEBUG_PATHS = DEBUG_CORRIDOR_STRUCTURE=1
DEBUG_FIX_WORLD = DEBUG_FIXED_WORLD=1
DEBUG_INPUT_CONTROLLS = DEBUG_INPUT_CONTROLLS=1

FULL_DEBUG = $(DEBUG_GRID) $(DEBUG_OBJECT_LABELS) $(DEBUG_ROOM_STRUCTURE) $(DEBUG_PATHS) $(DEBUG_FIX_WORLD) $(DEBUG_INPUT_CONTROLLS)
NO_LABEL_DEBUG = $(DEBUG_GRID) $(DEBUG_ROOM_STRUCTURE) $(DEBUG_PATHS) $(DEBUG_FIX_WORLD) $(DEBUG_INPUT_CONTROLLS)

#######
# Commands

run:
	$(GO) run main.go

run.debug:
	$(FULL_DEBUG) $(GO) run main.go

run.debug.nl:
	$(NO_LABEL_DEBUG) $(GO) run main.go
